### ISSUE TITLE
Need help to run the project

### ISSUE THREAD

**Issue by abhishekricky** [dherault/Zscan-INESS#1]
Hi,

Project looks awesome. As I m new to Rails

Need help to run 

I did 

sudo bundle install 

then rails s 

but project is not running

**Comment by dherault** [comment]
Hi @abhishekricky 

Have no idea how to start this 5+ yo project. I haven't used Ruby (or rails) since u_u'
I wouldn't advise you to use it for anything serious. It's rubbish (I've been developing web apps since).
